spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    expire_time: 10

api:
  openweathermap:
    appId: 13231e765fa010482d5397141f8bc303
    city: Ankara
    url: https://api.openweathermap.org/data/2.5/weather?q={city}&appid={appId}
    timeout: 5000
